CREATE DATABASE BANK_LOAN_PROJECT;

USE BANK_LOAN_PROJECT;

SELECT * FROM FINANCE_1;
SELECT * FROM FINANCE_2;

/* 

1) KPI 1 : YEAR WISE LOAN AMOUNT
2) KPI 2 : GRADE-SUBGRADE WISE REVOLUTION BALANCE
3) KPI 3 : TOTAL PAYMENT FOR VERIFIED STATUS VS NON VERIFIED STATUS
4) KPI 4 : STATE WISE LAST CREDIT PULL_D WISE LOAN STATUS
5) KPI 5 : HOME OWNERSHIP VS LAST PAYMENT DATE STATS.

*/

#KPI 1 : YEAR WISE LOAN AMOUNT

SELECT EXTRACT(YEAR FROM ISSUE_D) AS YEAR_OF_ISSUE_D, SUM(LOAN_AMNT) AS TOTAL_LOAN_AMOUNT
FROM FINANCE_1
GROUP BY YEAR_OF_ISSUE_D
ORDER BY YEAR_OF_ISSUE_D;

#KPI 2 : GRADE-SUBGRADE WISE REVOLUTION BALANCE

SELECT GRADE, SUB_GRADE, SUM(REVOL_BAL) AS TOTAL_REVOLUTION_BAL
FROM FINANCE_1 INNER JOIN FINANCE_2
ON FINANCE_1.ID = FINANCE_2.ID
GROUP BY GRADE, SUB_GRADE
ORDER BY GRADE, SUB_GRADE;

#KPI 3 : TOTAL PAYMENT FOR VERIFIED STATUS VS NON VERIFIED STATUS

SELECT VERIFICATION_STATUS, 
CONCAT("$", FORMAT(ROUND(SUM(TOTAL_PYMNT)/1000000),2),"M") AS TOTAL_PAYMENT
FROM FINANCE_1 INNER JOIN FINANCE_2
ON FINANCE_1.ID = FINANCE_2.ID
GROUP BY VERIFICATION_STATUS;

#KPI 4 : STATE WISE LAST CREDIT PULL_D WISE LOAN STATUS

SELECT ADDR_STATE, LAST_CREDIT_PULL_D, LOAN_STATUS
FROM FINANCE_1 INNER JOIN FINANCE_2
ON FINANCE_1.ID = FINANCE_2.ID
GROUP BY ADDR_STATE, LAST_CREDIT_PULL_D, LOAN_STATUS
ORDER BY LAST_CREDIT_PULL_D;

#KPI 5 : HOME OWNERSHIP VS LAST PAYMENT DATE STATS

SELECT HOME_OWNERSHIP, LAST_PYMNT_D,
CONCAT("$", FORMAT(ROUND(SUM(LAST_PYMNT_AMNT)/10000),2),"K") AS TOTAL_LAST_PAYMENT
FROM FINANCE_1 INNER JOIN FINANCE_2
ON FINANCE_1.ID = FINANCE_2.ID
GROUP BY HOME_OWNERSHIP, LAST_PYMNT_D
ORDER BY LAST_PYMNT_D DESC, HOME_OWNERSHIP DESC;
